### ISSUE TITLE
Depends on Normaliz 2.12

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/NormalizInterface#10]
Our current code does not work with Normaliz 2.11 (it does not even compile), so we require Normaliz >= 2.12

We should point that out in the README.

Also, if possible, perhaps we can add a test to configure to verify it is the right Normaliz version. Indeed, a basic test which test-compiles some code would be useful anyway. That code could then also check the normaliz version (if there is a way to do that using the normaliz headers), and / or it could check for some of the things which are new or different in 2.12.

As a last point, I am somewhat concerned about the fact that "libnormaliz" is rather unstable right now -- will 2.13 break compatibility once more? If so, that would mean that certain NormalizInterface require certain normaliz versions. We should document that then, too... And at that point, perhaps a libnormaliz-config tool and/or a pkg-config *.pc file for normaliz could be added, to make checking for the normaliz version easier...?

**Comment by csoeger** [comment]
For the upcoming version 3.0 of Normaliz there will be incompatible changes again. But from that on we will try to keep compatibility.
Anyway we will include a version number in the header, so that we could make adoptions if it gets necessary in the future, esp. for new features introduced to Normaliz.

**Comment by csoeger** [comment]
I included a version information into libnormaliz which we now can use like
`#if NMZ_RELEASE > 29900`
This will enable us to stay compatible with old versions. The question is how far do we want to be it? I will try to do it for the beta 2.99.1.
For Normaliz 3.0 we will change quite a lot of thinks. Most importantly the automatic decision of precision inside libnormaliz which will make our live in NormalizInterface much easier. But we only benefit from that if we don't have `#if`s everywhere.
I suggest we only try to stay compatible from version 3.0.0 on (or a beta 2.99.xx). We can checking for the NMZ_RELEASE and give an compile error saying we need a newer version of libnormaliz.
For all changes after 3.0.0 (hopefully only added features) we then should stay compatible.

**Comment by csoeger** [comment]
Implemented the changes as pointed out in the last post. The current version works with 2.12.x and 2.99.1.

But of course the behaviour is different in some details, e.g. some features (ClassGroup, NmzSetVerbose, ...) were not supported in 2.12 and therefore also not in NormalizInterface.

**Comment by fingolfin** [comment]
Based on recent discussions, we will simply make 3.0 a requirement.
