### ISSUE TITLE
FTBFS with a libnormaliz that's using e-antic

### ISSUE THREAD

**Issue by jengelh** [gap-packages/NormalizInterface#110]
e-antic-1.3.0
normaliz-3.9.4
NormalizInterface-1.3.5

* e-antic is a project that mandates at least C++14 due to the use of `std::add_lvalue_reference_t`.
* When normaliz is built with e-antic support, the `<libnormaliz/cone.h>` header will implicitly include `<e-antic/renfxx.h>`, and thereby require that all libnormaliz users have at least C++14 selected, too.
* NormalizInterface has this in configure.ac:
  ```sh
  AX_CXX_COMPILE_STDCXX(11, ,mandatory)
  ```
  which leads to `-std=c++11` being put on the compiler invocation command.

This makes `./configure` fail thus:

```
configure:3667: checking for libnormaliz/cone.h
configure:3667: g++ -std=gnu++11 -c -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g  -I/usr/include conftest.cpp >&5
In file included from /usr/include/e-antic/e-antic.hpp:20,
                 from /usr/include/e-antic/renfxx.h:19,
                 from /usr/include/libnormaliz/general.h:69,
                 from /usr/include/libnormaliz/cone.h:33,
                 from conftest.cpp:48:
/usr/include/e-antic/renf_class.hpp:245:10: error: 'add_lvalue_reference_t' in namespace 'std' does not name a template type; did you mean 'add_lvalue_reference'?
  245 |     std::add_lvalue_reference_t<::renf_t> renf_t() const { return nf; }
      |          ^~~~~~~~~~~~~~~~~~~~~~
[    6s] checking for libnormaliz/cone.h... no
[    6s] configure: error: could not use libnormaliz/cone.h
[    6s] $? = 1
```

**Comment by StefanBruens** [comment]
`--std=gnu++11` is also hardcoded in `Makefile.in`:
https://github.com/gap-packages/NormalizInterface/blob/9208ce4f962b506ac22f7f374fb50fd121bf373d/Makefile.in#L10

**Comment by fingolfin** [comment]
This package itself does not use any C++11 or C++14 features. The problem would not exist if there was a way to query the compile flags needed for Normaliz. I guess in some Linux distros there may be a pkgconfig file for it, if so, we could use that when present, and fall back to "guessing" when not.

**Comment by StefanBruens** [comment]
At least upstream does not provide on, there is an open issue (8 years old now):  
https://github.com/Normaliz/Normaliz/issues/114

**Comment by fingolfin** [comment]
Thinking about this again just now, I am not even sure pkg-config can solve this, logically, given that (a) flags for selecting the C++ standard may differ between compilers, (b) I am not sure whether one can gracefully "mix" these flags: perhaps Normaliz wants "at least C++14", but someone would like to use it in a project that needs "at least C++17" then of course the latter should "win". Oh and (c) I guess in this case it is not Normaliz that needs C++14 but rather its (optional) dependency e-antic.

**Comment by dimpase** [comment]
is there any real need to support anything older than C++14 ?

**Comment by fingolfin** [comment]
There are still users on systems with compilers not supporting C++14. But of course I can just "tough luck" and move on (or wait for them to complain *shrug*).
