### ISSUE TITLE
Interruption of libnormaliz computations

### ISSUE THREAD

**Issue by csoeger** [gap-packages/NormalizInterface#14]
As far as I understood, computations within GAP can always be interrupted in such a way that you can get back to the GAP interpreter and continue in some other way. That would also be nice to have for computations done by libnormaliz. Currently libnormaliz does not support it.

How does GAP promote it? Is it possible to give it to an external library?

One suggestion by John Abbott is the following: We assume the user (GAP, CoCoA, ...) of the library has a bool flag that is set to true if computations should be interrupted. The library has a  bool\* which can be set to point to that bool. And the library is then checking for that bool regularly and aborts the computation if it set. Would this also work for GAP?

This is not a high priority point. It will probably not make it into libnormaliz 3.0. I just like to hear if this could be a solution.

**Comment by fingolfin** [comment]
This would be great to have. In GAP, you can check the global variable `syLastIntr` (which is of type `Uint`, i.e. `unsigned int`); if it is non-zero, then an "interrupt" occured. So if there was an API in `libnormaliz` to either give it a pointer to that variable, or a pointer to a callback function (which would simply check that variable), then we could easily use that API from NormalizInterface.

**Comment by csoeger** [comment]
Leo Margolis just requested this feature.

**Comment by sebasguts** [comment]
This is implemented now.
