### ISSUE TITLE
sign-compare warning in IS_CONE macro

### ISSUE THREAD

**Issue by csoeger** [gap-packages/NormalizInterface#26]
I get multiple warnings like
```
src/normaliz.cc: In function 'UInt** _NmzCompute(Bag, Bag, Bag)':
src/normaliz.cc:345:115: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (!IS_CONE(cone))
```
Do we use the wrong type for `T_NORMALIZ`? Or should we just silence the warning?

**Comment by fingolfin** [comment]
Yeah, `T_NORMALIZ` should be an UInt (and I just made a commit to do that), simply because TNUM_OBJ returns an UInt. However, the values currently are always between 0 and 255, so this doesn't really have any effect, other than silencing the warning you get (I don't get it, BTW).
