### ISSUE TITLE
Bundle with normaliz

### ISSUE THREAD

**Issue by sebasguts** [gap-packages/NormalizInterface#3]
Would it make sense to bundle the package with normaliz, i.e. add normaliz as a git submodule to the repository. Maybe we can then compile it automatically with the package and add the path to this subdirectory as standard in the configure?

**Comment by fingolfin** [comment]
This is really interesting. We need to bundle (parts of) boost for this, and also ideally avoid having to use CMake. For the latter, we could ship a special Makefile for normaliz, which we generate with our own configure script...

**Comment by fingolfin** [comment]
For boost, we can use `bcp` (see [here](http://www.boost.org/doc/libs/1_59_0/tools/bcp/doc/html/index.html)) to extract only those parts we need (which is only `dynamic_bitset` right now), then bundle that with our code.

**Comment by fingolfin** [comment]
We decided against bundling boost (or even just parts of it) because it is so big (multiple megabytes of source code), even when using the `bcp` tool.

**Comment by csoeger** [comment]
We don't want to bundle boost, and for normaliz we have a nice download/build script. So I guess the only advantage we could gain is that one does not need to have git installed. But for that I don't think its worth it and we can close this issue.
