### ISSUE TITLE
Clarify: "Normaliz" or "normaliz"

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/NormalizInterface#31]
What is the preffered spelling of the "Normaliz" project? Normally, I would spell it like that (uppercase), but there are also lots of places in our code base where it is spelled as "normaliz". E.g. sometimes we take about a "Normaliz cone" and sometimes about a "normaliz cone". That's a fairly minor issue, but I still think we should settle on one and use that consistently.

**Comment by sebasguts** [comment]
I would say Normaliz from their website http://www.home.uni-osnabrueck.de/wbruns/normaliz/, but of course @csoeger is the expert here

**Comment by fingolfin** [comment]
Yeah, makes sense. I changed it to be like that in bcc7b35d5a781f80d0a2d6b83ef6f438f88330c4 but of course we can always change it in the other direction again if @csoeger tells us so.

**Comment by csoeger** [comment]
Right, the official spelling is with upper case N.
