### ISSUE TITLE
File permissions

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/NormalizInterface#37]
Files in the `doc` directory do not have 644 permissions. Instead, they are not readable by group and others.

**Comment by alex-konovalov** [comment]
P.S. It was reported by one of the package authors who installed GAP 4.8.2 that there are files in other directories having the same problem.

**Comment by alex-konovalov** [comment]
P.P.S. Please see also another report: https://mail.gap-system.org/pipermail/gap/2016-February/000578.html

**Comment by fingolfin** [comment]
I am not quite sure how that happened. I think @csoeger made the last releaes. Perhaps he is using a non-standard umask, like 0077?

**Comment by fingolfin** [comment]
I just released 0.9.6, whose tarballs contain correct permissions. It also updates to Normaliz 3.1.0. 

So I hope this will be picked up for GAP 4.8.3 (which I guess should be made relatively soon)

**Comment by fingolfin** [comment]
I also improved ReleaseTools, it now calls `umask 0022`, which should hopefully avoid similar problems in the future, at least for packages using ReleaseTools.
