### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by mohamed-barakat** [gap-packages/NormalizInterface#42]
While building NormalizInterface with

./build-normaliz.sh

for gap 4.8.4 on my Mac OS X 10.10 with Fink 0.39.5 I got the following error

Found GAP in directory /Users/mo/software/gap/gap_current
GAParch = x86_64-apple-darwin14.5.0--default64
GAP was built with external GMP
-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS)
-- Not using OpenMP, compiler does not support it
-- Found GMP: /sw/lib/gmp5/libgmp.dylib
-- GMP found with include dir: /sw/include
-- GMP found with lib dir: /sw/lib/gmp5
-- GMP found with lib : /sw/lib/gmp5/libgmp.dylib
-- GMP found with static lib : /sw/lib/gmp5/libgmp.a
-- Found GMPXX: /sw/lib/gmp5/libgmpxx.dylib
-- GMPXX found with include dir: /sw/include
-- GMPXX found with lib : /sw/lib/gmp5/libgmpxx.dylib
-- GMPXX found with static lib : /sw/lib/gmp5/libgmpxx.a
-- Boost version: 1.53.0
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mo/software/pkg/NormalizInterface/Normaliz.git/BUILD
Scanning dependencies of target normaliz-shared
[ 11%] Building CXX object libnormaliz/CMakeFiles/normaliz-shared.dir/cone_property.cpp.o
[ 22%] Building CXX object libnormaliz/CMakeFiles/normaliz-shared.dir/HilbertSeries.cpp.o
[ 33%] Building CXX object libnormaliz/CMakeFiles/normaliz-shared.dir/libnormaliz-templated.cpp.o
[ 44%] Building CXX object libnormaliz/CMakeFiles/normaliz-shared.dir/cone_helper.cpp.o
[ 55%] Building CXX object libnormaliz/CMakeFiles/normaliz-shared.dir/offload_handler.cpp.o
[ 66%] Building CXX object libnormaliz/CMakeFiles/normaliz-shared.dir/bottom.cpp.o
[ 77%] Linking CXX shared library libnormaliz.dylib
[ 77%] Built target normaliz-shared
Scanning dependencies of target normaliz
[ 88%] Building CXX object CMakeFiles/normaliz.dir/Normaliz.cpp.o
[100%] Linking CXX executable normaliz
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > libnormaliz::toString<long>(long)", referenced from:
      std::__1::map<libnormaliz::Type::InputType, std::__1::vector<std::__1::vector<__gmp_expr<__mpz_struct [1], __mpz_struct [1]>, std::__1::allocator<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> > >, std::__1::allocator<std::__1::vector<__gmp_expr<__mpz_struct [1], __mpz_struct [1]>, std::__1::allocator<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> > > > >, std::__1::lesslibnormaliz::Type::InputType, std::__1::allocator<std::__1::pair<libnormaliz::Type::InputType const, std::__1::vector<std::__1::vector<__gmp_expr<__mpz_struct [1], __mpz_struct [1]>, std::__1::allocator<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> > >, std::__1::allocator<std::__1::vector<__gmp_expr<__mpz_struct [1], __mpz_struct [1]>, std::__1::allocator<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> > > > > > > > readNormalizInput<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, OptionsHandler&) in Normaliz.cpp.o
      std::__1::map<libnormaliz::Type::InputType, std::__1::vector<std::__1::vector<long long, std::__1::allocator<long long> >, std::__1::allocator<std::__1::vector<long long, std::__1::allocator<long long> > > >, std::__1::lesslibnormaliz::Type::InputType, std::__1::allocator<std::__1::pair<libnormaliz::Type::InputType const, std::__1::vector<std::__1::vector<long long, std::__1::allocator<long long> >, std::__1::allocator<std::__1::vector<long long, std::__1::allocator<long long> > > > > > > readNormalizInput<long long>(std::__1::basic_istream<char, std::__1::char_traits<char> >&, OptionsHandler&) in Normaliz.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/normaliz.dir/build.make:97: recipe for target 'normaliz' failed
make[2]: **\* [normaliz] Error 1
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/normaliz.dir/all' failed
make[1]: **\* [CMakeFiles/normaliz.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

Note: I built gap to use the system gmp and not the one shipped with gap.

**Comment by mohamed-barakat** [comment]
Compile error reproducible with
* official gap 4.8.6
* on a Mac OS X (10.12.3 (16D32)).
* fink version 0.41.1

**Comment by sebasguts** [comment]
This was solved by switching to the new Normaliz build system
