### ISSUE TITLE
Make sure install / compile instructions are up-to-date

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/NormalizInterface#5]
I.e. write a README or INSTALL file that explains how to get into a state where one can actually use the package. Perhaps take some inspiration from the libsing INSTALL file.

It should explain how to get and compile Normaliz; and then how to compile NormalizeInterface from there.

On Mac OS X, doing that was a bit tricky. In the end, I had to choose between disabling openmp support (as the default compiler, clang, resp. llvm-gcc 4.2, does not seem to support it), or using GCC 4.8 (which is not shipped with the system, and so most people won't have it; moreover, using it with OpenMP enabled only worked for me once I also manually modified GAP's "gac" script, something we shouldn't try to get regular users to do).

**Comment by fingolfin** [comment]
We seem to be in a pretty good shape in this regard now, but before a release, we should verify everything is in place. And maybe ask some volunteers to test our instructions, and tell us if they find them clear enough.

**Comment by csoeger** [comment]
With the new build_normaliz.sh it is quite easy and well discribed. We could also add a section about how to update the existing installation, i.e. using git pull and rebuilding.

A second minor point is the other GAP packages we use. We mention io, should we also mention GAPDoc and AutoDoc? These I had to add when I was using the git version of gap. But I think they are included in the distributed version of gap, so there is no need.

**Comment by fingolfin** [comment]
GAPDoc is a required package, i.e. GAP does not even start without it. And AutoDoc is only needed to build the documentation, but not to load NormalizInterface.

**Comment by csoeger** [comment]
io is also only needed for running the tests, and there we also use AutoDoc which creates the `maketest.g` file.

**Comment by fingolfin** [comment]
I think this is complete now.
