### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by HereAround** [gap-packages/NormalizInterface#59]
I run gap 4.10.0 on Ubuntu 18.04.1 and just cloned NormalizInterface, but cannot get it running. Here are my steps:

(1) ./build-normaliz.sh GAPDir
(2) ./autogen.sh
(3) ./configure --with-gaproot=GAPDir
(4) make

The output from make is:

  CXX      src/NormalizInterface_la-normaliz.lo
src/normaliz.cc:1018:1: sorry, unimplemented: non-trivial designated initializers not supported
 };
 ^
src/normaliz.cc:1018:1: sorry, unimplemented: non-trivial designated initializers not supported
Makefile:533: recipe for target 'src/NormalizInterface_la-normaliz.lo' failed
make: *** [src/NormalizInterface_la-normaliz.lo] Error 1

and the package still fails to load.

**Comment by HereAround** [comment]
I cloned from

https://github.com/homalg-project/NormalizInterface.git 

It seems that this caused this problem, as in contrast the latest shipped version (https://www.gap-system.org/Packages/normalizinterface.html) works fine for me.

**Comment by sebasguts** [comment]
Exactly. This bug does not appear for the latest version.
