### ISSUE TITLE
No such file or directory during make

### ISSUE THREAD

**Issue by lmyreg2017** [gap-packages/NormalizInterface#88]
I obtained the error above on the following system:

- Ubuntu 18.04 (in Google Cloud Platform)
- gap 4.10.1
- Normaliz 3.5.4 (ce7b4caf98ddcfe0a421f262d0e3a64cd27d053d)

./build-normaliz and ./configure complete successfully. However, make raises the following:

CXXLD    NormalizInterface.la

*** Warning: Linking the shared library NormalizInterface.la against the
*** static library /home/lmyreg2017/gap-4.10.1/extern/install/zlib/lib/libz.a is not portable!
g++: error: /home/lmyreg2017/gap-4.10.1/extern/install/zlib/lib/libz.a: No such file or directory
Makefile:495: recipe for target 'NormalizInterface.la' failed
make: *** [NormalizInterface.la] Error 1

**Comment by fingolfin** [comment]
Looks as if your copy of GAP was compiled with a builtin zlib; that causes issues. I think we fixed that in gap 4.10.2 (or if not there, then definitely in GAP 4.11),, *but* the easiest way to fix this for good is to install the `zlib1g-dev` package on your Ubuntu system (in addition to gmp and readline packages), i.e.:
```shell
sudo apt install zlib1g-dev  libgmp-dev libreadline-dev
```
Then, recompile GAP, i.e. do the full `./configure && make` again. Finally, try to compile NormalizInterface, it should work.

**Comment by lmyreg2017** [comment]
Thanks a lot for thd re

**Comment by lmyreg2017** [comment]
Thanks
