### ISSUE TITLE
make check

### ISSUE THREAD

**Issue by csoeger** [gap-packages/NormalizInterface#9]
For me "make check" get stuck and does not exit, even ctrl-c does not exits it. A manual "gap tst/testall.g" gives
      Syntax error: warning: unbound global variable in testall.g line 100
      IO_exit(0); # make check: PASSED

The problem is that I hadn't compiled the io package, afterwards it works fine. But it should be more robust and check for the io package.

**Comment by csoeger** [comment]
Problem still exists. But I noticed pressing ctrl-d twice exit it.
I added the dependence on package io in the README.

Should we simply let the NormalizInterface package depend on io? Probably not the right way to do it.

**Comment by fingolfin** [comment]
No, "io" should not be a dep. This is a bug in the test setup which I need to fix.
