### ISSUE TITLE
Installation of NormalizInterface in Julia

### ISSUE THREAD

**Issue by HereAround** [gap-packages/NormalizInterface#96]
I am trying to use `NormalizInterface` in Julia. My system is Ubuntu 18.04 and I have Julia 1.5.2 (2020-09-23). It seems the following fails to install the package:

> using GAP
GAP.Packages.install( "NormalizInterface" )
#I  Getting PackageInfo URLs...
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/NormalizInterface/PackageInfo.g ...
#I  Downloading archive from URL https://github.com/gap-packages/NormalizInterface/releases/download/v1.2.0/NormalizInterface-1.2.0.tar.gz ...
#I  Saved archive to /tmp/tmsJytm0/NormalizInterface-1.2.0.tar.gz
#I  Extracting to /home/i/.julia/gaproot/v4.11/pkg/NormalizInterface-1.2.0 ...
#I  Running compilation script on /home/i/.julia/gaproot/v4.11/pkg/NormalizInterface-1.2.0 ...
#I  Package availability test failed
#I  (for NormalizInterface 1.2.0)
#I  Removed directory /home/i/.julia/gaproot/v4.11/pkg/NormalizInterface-1.2.0
false

In the `PackageInfo`, I see only a dependency on `GAP := ">= 4.9"`. My Julia uses `GAP 4.11.0-65-g42b0b58-dirty of 29-Feb-2020`. Hence, I fail to make sense of the message `Package availability test failed`.

Am I missing something obvious?

**Comment by fingolfin** [comment]
@HereAround sorry, I've been (and still am) tied up in various workshops, so things are slow going).

In principle, it should be possible to get this working; I think what we see here is more a subtle issue with the GAP PackageManager package, or at least that PackageManager makes it harder to debug this (see also https://github.com/gap-packages/PackageManager/issues/66).

It seems that that while it manages to build the package, it then fails to load it for some reason -- and then deletes it, making it hard to debug. Perhaps if you set `SetInfoLevel(InfoPackageLoading, 4);` before trying to install the package, we'll get some more info (perhaps I can even reproduce it myself, I unfortunately did not yet have a chance to try that).

Right now I don't even know if the above commands compiled the normaliz bundled with NormalizInterface, or tried to use an existing one... on the long run, we certainly want it to use the normaliz that we bundle as a Julia JLL for use in Oscar anyway (but then one has to also  be careful about which version that is, so that the NormalizInterface kernel extension can talk to it).

All in all, this can be resolved, but it requires some technical skills (which I have) and time (which I am very much short of these days)...

**Comment by HereAround** [comment]
Thank you @fingolfin. And no worries!

I have investigate a bit more. First, I tried to uninstall `NormalizInterface`, so that the unsuccessful installation would not lead to any artifacts. It seems that this was not successful:

> GAP.Globals.SetInfoLevel(GAP.Globals.InfoPackageLoading,4);
julia> GAP.Packages.remove( "NormalizInterface" );
#I  PackageManager: entering LoadPackage 
#I  PackageManager: return from LoadPackage, package was already loaded
#I  Package "NormalizInterface" not installed in user package directory
#I  (currently set to /home/i/.julia/gaproot/v4.11/pkg)
#I  installed at [ "/home/i/.julia/artifacts/848f0f318405266896d24d11e4baf5cf7bf3f203/gap-4.11.0/pkg/NormalizInterface-1.1.0" ], not in /home/i/.julia/gaproot/v4.11/pkg

I do not know if this is something to worry about, but wanted to mention it...

A new attempt to install `Normalizinterface` now leads to the following:

> GAP.Packages.install( "NormalizInterface" )
#I  PackageManager: entering LoadPackage 
#I  PackageManager: return from LoadPackage, package was already loaded
#I  Getting PackageInfo URLs...
#I  curlInterface: PackageAvailabilityInfo for version 2.1.1
#I                 (required: >= 2.1.0)
#I  curlInterface: kernel extension not compiled, package cannot be loaded
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  curlInterface: PackageAvailabilityInfo: no installed version fits
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/NormalizInterface/PackageInfo.g ...
#I  curlInterface: PackageAvailabilityInfo for version 2.1.1
#I                 (required: >= 2.1.0)
#I  curlInterface: kernel extension not compiled, package cannot be loaded
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  curlInterface: PackageAvailabilityInfo: no installed version fits
#I  Downloading archive from URL https://github.com/gap-packages/NormalizInterface/releases/download/v1.2.0/NormalizInterface-1.2.0.tar.gz ...
#I  curlInterface: PackageAvailabilityInfo for version 2.1.1
#I                 (required: >= 2.1.0)
#I  curlInterface: kernel extension not compiled, package cannot be loaded
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  curlInterface: PackageAvailabilityInfo: no installed version fits
#I  Saved archive to /tmp/tm5tMiqu/NormalizInterface-1.2.0.tar.gz
#I  Extracting to /home/i/.julia/gaproot/v4.11/pkg/NormalizInterface-1.2.0 ...
#I  GAP: entering InitializePackagesInfoRecords
#I  GAP: return from InitializePackagesInfoRecords
#I  NormalizInterface: PackageAvailabilityInfo for version 1.2.0
#I                     (required: 1.2.0)
#I  NormalizInterface: kernel functions for NormalizInterface not available.
#I  NormalizInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  NormalizInterface: PackageAvailabilityInfo: version 1.1.0 does not fit
#I                     (required: 1.2.0)
#I  NormalizInterface: PackageAvailabilityInfo: no installed version fits
#I  Running compilation script on /home/i/.julia/gaproot/v4.11/pkg/NormalizInterface-1.2.0 ...
#I  NormalizInterface: PackageAvailabilityInfo for version 1.2.0
#I                     (required: 1.2.0)
#I  NormalizInterface: kernel functions for NormalizInterface not available.
#I  NormalizInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  NormalizInterface: PackageAvailabilityInfo: version 1.1.0 does not fit
#I                     (required: 1.2.0)
#I  NormalizInterface: PackageAvailabilityInfo: no installed version fits
#I  GAP: entering InitializePackagesInfoRecords
#I  GAP: return from InitializePackagesInfoRecords
#I  NormalizInterface: PackageAvailabilityInfo for version 1.2.0
#I                     (required: 1.2.0)
#I  NormalizInterface: kernel functions for NormalizInterface not available.
#I  NormalizInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  NormalizInterface: PackageAvailabilityInfo: version 1.1.0 does not fit
#I                     (required: 1.2.0)
#I  NormalizInterface: PackageAvailabilityInfo: no installed version fits
#I  Package availability test failed
#I  (for NormalizInterface 1.2.0)
#I  Removed directory /home/i/.julia/gaproot/v4.11/pkg/NormalizInterface-1.2.0
#I  GAP: entering InitializePackagesInfoRecords
#I  GAP: return from InitializePackagesInfoRecords
false

Since the shipped version of `curlInterface` does not satisfy the above dependency, I installed it:

> GAP.Packages.install( "curlInterface" )
#I  PackageManager: entering LoadPackage
#I  PackageManager: return from LoadPackage, package was already loaded
#I  Getting PackageInfo URLs...
#I  curlInterface: PackageAvailabilityInfo for version 2.1.1
#I                 (required: >= 2.1.0)
#I  curlInterface: kernel extension not compiled, package cannot be loaded
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  curlInterface: PackageAvailabilityInfo: no installed version fits
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/curlInterface/PackageInfo.g ...
#I  curlInterface: PackageAvailabilityInfo for version 2.1.1
#I                 (required: >= 2.1.0)
#I  curlInterface: kernel extension not compiled, package cannot be loaded
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  curlInterface: PackageAvailabilityInfo: no installed version fits
#I  Downloading archive from URL https://github.com/gap-packages/curlInterface/releases/download/v2.2.1/curlInterface-2.2.1.tar.gz ...
#I  curlInterface: PackageAvailabilityInfo for version 2.1.1
#I                 (required: >= 2.1.0)
#I  curlInterface: kernel extension not compiled, package cannot be loaded
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  curlInterface: PackageAvailabilityInfo: no installed version fits
#I  Saved archive to /tmp/tmJRBDEO/curlInterface-2.2.1.tar.gz
#I  Extracting to /home/i/.julia/gaproot/v4.11/pkg/curlInterface-2.2.1 ...
#I  Checking dependencies for curlInterface...
#I    GAPDoc >= 1.5: true
#I  curlInterface: PackageAvailabilityInfo for version 2.1.1
#I                 (required: >= 2.1.0)
#I  curlInterface: kernel extension not compiled, package cannot be loaded
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  curlInterface: PackageAvailabilityInfo: no installed version fits
#I  GAP: entering InitializePackagesInfoRecords
#I  GAP: return from InitializePackagesInfoRecords
#I  GAP: entering InitializePackagesInfoRecords
#I  GAP: return from InitializePackagesInfoRecords
#I  curlInterface: PackageAvailabilityInfo for version 2.2.1
#I                 (required: 2.2.1)
#I  curlInterface: kernel extension not compiled, package cannot be loaded
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  curlInterface: PackageAvailabilityInfo: version 2.1.1 does not fit
#I                 (required: 2.2.1)
#I  curlInterface: PackageAvailabilityInfo: no installed version fits
#I  Running compilation script on /home/i/.julia/gaproot/v4.11/pkg/curlInterface-2.2.1 ...
#I  curlInterface: PackageAvailabilityInfo for version 2.2.1
#I                 (required: 2.2.1)
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned 'true'
#I  curlInterface: PackageAvailabilityInfo: check needed packages
#I                 GAPDoc (>= 1.5)
#I  curlInterface: PackageAvailabilityInfo: check of needed packages done
#I  curlInterface: PackageAvailabilityInfo: version 2.2.1 is available
#I  GAP: entering InitializePackagesInfoRecords
#I  GAP: return from InitializePackagesInfoRecords
#I  curlInterface: PackageAvailabilityInfo for version 2.2.1
#I                 (required: 2.2.1)
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned 'true'
#I  curlInterface: PackageAvailabilityInfo: check needed packages
#I                 GAPDoc (>= 1.5)
#I  curlInterface: PackageAvailabilityInfo: check of needed packages done
#I  curlInterface: PackageAvailabilityInfo: version 2.2.1 is available
#I  GAP: entering InitializePackagesInfoRecords
#I  GAP: return from InitializePackagesInfoRecords
true

It loads successfully:

> GAP.Packages.load( "curlInterface" )
#I  curlInterface: entering LoadPackage 
#I  curlInterface: PackageAvailabilityInfo for version 2.2.1
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned 'true'
#I  curlInterface: PackageAvailabilityInfo: check needed packages
#I                 GAPDoc (>= 1.5)
#I  curlInterface: PackageAvailabilityInfo: check of needed packages done
#I  curlInterface: PackageAvailabilityInfo: check suggested packages
#I  curlInterface: PackageAvailabilityInfo: check of suggested packages done
#I  curlInterface: PackageAvailabilityInfo: version 2.2.1 is available
#I  curlInterface: start loading needed/suggested/self packages
#I                 curlinterface
#I  curlInterface: start reading file 'init.g'
#W BIND_GLOBAL: variable `DownloadURL' already has a value
#I  curlInterface: finish reading file 'init.g'
#I  curlInterface: start reading file 'read.g'
#I  curlInterface: finish reading file 'read.g'
#I  curlInterface: return from LoadPackage
true

So back to `NormalizInterface`:

> julia> GAP.Globals.SetInfoLevel(GAP.Globals.InfoPackageLoading,4);
julia> GAP.Packages.install( "NormalizInterface" )
#I  PackageManager: entering LoadPackage 
#I  PackageManager: PackageAvailabilityInfo for version 1.0
#I  PackageManager: PackageAvailabilityInfo: the AvailabilityTest function returned 'true'
#I  PackageManager: PackageAvailabilityInfo: check needed packages
#I                  GAPDoc (>= 1.6.1)
#I  PackageManager: PackageAvailabilityInfo: check of needed packages done
#I  PackageManager: PackageAvailabilityInfo: check suggested packages
#I                  curlInterface (>= 2.1.0)
#I  curlInterface: PackageAvailabilityInfo for version 2.2.1
#I                 (required: >= 2.1.0)
#I  curlInterface: PackageAvailabilityInfo: the AvailabilityTest function returned 'true'
#I  curlInterface: PackageAvailabilityInfo: check needed packages
#I                 GAPDoc (>= 1.5)
#I  curlInterface: PackageAvailabilityInfo: check of needed packages done
#I  curlInterface: PackageAvailabilityInfo: check suggested packages
#I  curlInterface: PackageAvailabilityInfo: check of suggested packages done
#I  curlInterface: PackageAvailabilityInfo: version 2.2.1 is available
#I  PackageManager: PackageAvailabilityInfo: check of suggested packages done
#I  PackageManager: PackageAvailabilityInfo: version 1.0 is available
#I  PackageManager: start loading needed/suggested/self packages
#I                  curlinterface
#I  curlInterface: start reading file 'init.g'
#I  curlInterface: finish reading file 'init.g'
#I  curlInterface: start reading file 'read.g'
#I  curlInterface: finish reading file 'read.g'
#I  PackageManager: start loading needed/suggested/self packages
#I                  packagemanager
#I  PackageManager: start reading file 'init.g'
#I  PackageManager: finish reading file 'init.g'
#I  PackageManager: start reading file 'read.g'
#I  PackageManager: finish reading file 'read.g'
#I  PackageManager: return from LoadPackage
#I  Getting PackageInfo URLs...
julia: symbol lookup error: /home/i/.julia/gaproot/v4.11/pkg/curlInterface-2.2.1/bin/x86_64-pc-linux-gnu-julia64-kv7/curl.so: undefined symbol: curl_global_init

This new error indicates a potential problems with `curlInterface`.
